DROP
DATABASE IF EXISTS BIOMEDICA;

CREATE
DATABASE BIOMEDICA;

USE
BIOMEDICA;

CREATE TABLE SEXO
(
    ID           INT AUTO_INCREMENT PRIMARY KEY,
    DESCRIPCCION CHAR(1)
);

CREATE TABLE TELEFONO
(
    ID     INT AUTO_INCREMENT PRIMARY KEY,
    NUMERO BIGINT
);

CREATE TABLE DOMICILIO
(
    ID     INT AUTO_INCREMENT PRIMARY KEY,
    CALLE  VARCHAR(30),
    ALTURA INT
);

CREATE TABLE UNIDAD_DE_MEDIDA
(
    ID     INT AUTO_INCREMENT PRIMARY KEY,
    UNIDAD VARCHAR(10)
);

CREATE TABLE METODO
(
    ID           INT AUTO_INCREMENT PRIMARY KEY,
    DESCRIPCCION VARCHAR(10)
);

CREATE TABLE EXTRACCIONISTA
(
    ID       INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE   VARCHAR(50),
    APELLIDO VARCHAR(50)
);

CREATE TABLE ESTADO
(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    DESCRIPCCION VARCHAR(20)
);

CREATE TABLE ESTUDIO
(
    ID                  INT AUTO_INCREMENT PRIMARY KEY,
    DESCRIPCCION        VARCHAR(50),
    RANGO_REFERENCIA    VARCHAR(10),
    ID_METODO           INT,
    ID_UNIDAD_DE_MEDIDA INT,
    CONSTRAINT `ESTUDIO->METODO` FOREIGN KEY (ID_METODO) REFERENCES METODO (ID),
    CONSTRAINT `ESTUDIO->UNIDAD_DE_MEDIDA` FOREIGN KEY (ID_UNIDAD_DE_MEDIDA) REFERENCES UNIDAD_DE_MEDIDA (ID)
);

CREATE TABLE RESULTADO
(
    ID            INT AUTO_INCREMENT PRIMARY KEY,
    VALOR_HALLADO INT,
    FECHA         DATE,
    ID_ESTUDIO    INT,
    CONSTRAINT `RESULTADO->ESTUDIO` FOREIGN KEY (ID_ESTUDIO) REFERENCES ESTUDIO (ID)
);

CREATE TABLE MUESTRA
(
    ID            INT AUTO_INCREMENT PRIMARY KEY,
    DESCRIPCCION  VARCHAR(50),
    FECHA_DE_TOMA DATE,
    ID_RESULTADO  INT,
    CONSTRAINT `MUESTRA->RESULTADO` FOREIGN KEY (ID_RESULTADO) REFERENCES RESULTADO (ID)
);

CREATE TABLE PACIENTE
(
    ID           INT PRIMARY KEY,
    DNI          INT,
    NOMBRE       VARCHAR(50),
    APELLIDO     VARCHAR(50),
    ID_SEXO      INT,
    ID_DOMICILIO INT,
    ID_TELEFONO  INT,
    EMAIL        VARCHAR(100),
    CONSTRAINT `PACIENTE->SEXO` FOREIGN KEY (ID_SEXO) REFERENCES SEXO (ID),
    CONSTRAINT `PACIENTE->DOMICILIO` FOREIGN KEY (ID_DOMICILIO) REFERENCES DOMICILIO (ID),
    CONSTRAINT `PACIENTE->TELEFONO` FOREIGN KEY (ID_TELEFONO) REFERENCES TELEFONO (ID)
);

