DROP DATABASE IF EXISTS BIOMEDICA;

CREATE DATABASE BIOMEDICA;

USE BIOMEDICA;

CREATE TABLE SEXO
(
    ID           INT AUTO_INCREMENT PRIMARY KEY,
    DESCRIPCCION CHAR(1)
);

CREATE TABLE TELEFONO
(
    ID     INT AUTO_INCREMENT PRIMARY KEY,
    NUMERO BIGINT
);

CREATE TABLE DOMICILIO
(
    ID     INT AUTO_INCREMENT PRIMARY KEY,
    CALLE  VARCHAR(30),
    ALTURA INT
);

CREATE TABLE PACIENTE
(
    ID           INT PRIMARY KEY,
    DNI          INT,
    NOMBRE       VARCHAR(50),
    APELLIDO     VARCHAR(50),
    ID_SEXO      INT,
    ID_DOMICILIO INT,
    ID_TELEFONO  INT,
    EMAIL        VARCHAR(100),
    CONSTRAINT `PACIENTE->SEXO` FOREIGN KEY (ID_SEXO) REFERENCES SEXO (ID),
    CONSTRAINT `PACIENTE->DOMICILIO` FOREIGN KEY (ID_DOMICILIO) REFERENCES DOMICILIO (ID),
    CONSTRAINT `PACIENTE->TELEFONO` FOREIGN KEY (ID_TELEFONO) REFERENCES TELEFONO (ID)
);