# Generated by Django 4.1.2 on 2022-11-18 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domicilio',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('calle', models.CharField(blank=True, db_column='CALLE', max_length=30, null=True)),
                ('altura', models.IntegerField(blank=True, db_column='ALTURA', null=True)),
                ('n_piso', models.IntegerField(blank=True, db_column='N_PISO', null=True)),
                ('departamento', models.CharField(blank=True, db_column='DEPARTAMENTO', max_length=15, null=True)),
            ],
            options={
                'db_table': 'DOMICILIO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoDeSolicitud',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='NOMBRE', max_length=20, null=True)),
                ('descripccion', models.TextField(blank=True, db_column='DESCRIPCCION', null=True)),
            ],
            options={
                'db_table': 'ESTADO_DE_SOLICITUD',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estudio',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='NOMBRE', max_length=50, null=True)),
                ('descripccion', models.TextField(blank=True, db_column='DESCRIPCCION', null=True)),
                ('limite_inferior', models.FloatField(blank=True, db_column='LIMITE_INFERIOR', null=True)),
                ('limite_superior', models.FloatField(blank=True, db_column='LIMITE_SUPERIOR', null=True)),
            ],
            options={
                'db_table': 'ESTUDIO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Extraccionista',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='NOMBRE', max_length=50, null=True)),
                ('apellido', models.CharField(blank=True, db_column='APELLIDO', max_length=50, null=True)),
            ],
            options={
                'db_table': 'EXTRACCIONISTA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('matricula', models.CharField(blank=True, db_column='MATRICULA', max_length=13, null=True)),
                ('nombre', models.CharField(blank=True, db_column='NOMBRE', max_length=50, null=True)),
                ('apellido', models.CharField(blank=True, db_column='APELLIDO', max_length=50, null=True)),
            ],
            options={
                'db_table': 'MEDICO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Metodo',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='NOMBRE', max_length=30, null=True)),
                ('descripccion', models.TextField(blank=True, db_column='DESCRIPCCION', null=True)),
            ],
            options={
                'db_table': 'METODO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Muestra',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('descripccion', models.TextField(blank=True, db_column='DESCRIPCCION', null=True)),
                ('fecha_hora_extraccion', models.DateTimeField(blank=True, db_column='FECHA_HORA_EXTRACCION', null=True)),
            ],
            options={
                'db_table': 'MUESTRA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('n_documento', models.IntegerField(blank=True, db_column='N_DOCUMENTO', null=True)),
                ('nombre', models.CharField(blank=True, db_column='NOMBRE', max_length=50, null=True)),
                ('apellido', models.CharField(blank=True, db_column='APELLIDO', max_length=50, null=True)),
                ('email', models.CharField(blank=True, db_column='EMAIL', max_length=100, null=True)),
                ('contraseña', models.CharField(blank=True, db_column='CONTRASEÑA', max_length=100, null=True)),
            ],
            options={
                'db_table': 'PACIENTE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('valor_hallado', models.FloatField(blank=True, db_column='VALOR_HALLADO', null=True)),
                ('fecha', models.DateField(blank=True, db_column='FECHA', null=True)),
                ('observacion', models.TextField(blank=True, db_column='OBSERVACION', null=True)),
            ],
            options={
                'db_table': 'RESULTADO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='NOMBRE', max_length=15, null=True)),
                ('descripccion', models.TextField(blank=True, db_column='DESCRIPCCION', null=True)),
            ],
            options={
                'db_table': 'SEXO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('receta', models.CharField(blank=True, db_column='RECETA', max_length=100, null=True)),
                ('fecha_hora_inicio', models.DateTimeField(blank=True, db_column='FECHA_HORA_INICIO', null=True)),
                ('fecha_hora_finalizacion', models.DateTimeField(blank=True, db_column='FECHA_HORA_FINALIZACION', null=True)),
                ('cap', models.CharField(blank=True, db_column='CAP', max_length=8, null=True)),
            ],
            options={
                'db_table': 'SOLICITUD',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('numero', models.BigIntegerField(blank=True, db_column='NUMERO', null=True)),
            ],
            options={
                'db_table': 'TELEFONO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoDeDocumento',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='NOMBRE', max_length=15, null=True)),
                ('descripcion', models.TextField(blank=True, db_column='DESCRIPCION', null=True)),
            ],
            options={
                'db_table': 'TIPO_DE_DOCUMENTO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UnidadDeMedida',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('unidad', models.CharField(blank=True, db_column='UNIDAD', max_length=15, null=True)),
                ('descripcion', models.TextField(blank=True, db_column='DESCRIPCION', null=True)),
            ],
            options={
                'db_table': 'UNIDAD_DE_MEDIDA',
                'managed': False,
            },
        ),
    ]
