@startuml BIOMEDICA
entity Medico {
    * id
    --
    * matricula
    * nombre
    * apellido
}

entity Domicilio {
    * id
    --
    * calle
    * altura
}

entity Telefono {
    * id
    --
    * numero
}

entity Sexo {
    * id
    --
    * descripcion
}

entity Paciente {
    * numero
    --
    * dni
    * nombre
    * apellido
    * id_sexo
    * id_domicilio
    * id_telefono
    * email
}

entity Estado {
    * id
    --
    * descripcion
}

entity Estudio {
    * id
    --
    * descripcion
    * rangos_de_referencias
    * id_metodo
    * id_unidad_de_medida
}

entity Solicitud {
    * id
    --
    * receta
    * id_extraccionista
    * id_estado
    * id_medico
    * fecha
    * hora
    * CAP
}

entity Extraccionista {
    * id
    --
    * nombre
    * apellido
}

entity Muestra {
    * id
    --
    * descripcion
    * fecha
    * id_solicitud
}

entity Metodo {
    * id
    --
    * descripcion
}

entity Resultado {
    * id
    --
    * valor_hallado
    * fecha
    * id_estudio
}

entity UnidadDeMedida {
    * id
    --
    * unidad
}

Paciente ||..|| Domicilio
Paciente ||..|{ Telefono
Paciente }o..|| Sexo
Paciente ||..|{ Solicitud
Solicitud }o..|| Medico
Solicitud }o..|| Estado
Resultado ||..o| Muestra
Solicitud }o..|| Extraccionista
Estudio }o..|| Metodo
Solicitud }|..|{ Resultado
Estudio }o..|| UnidadDeMedida
Resultado }o..|| Estudio

@enduml