@startuml BIOMEDICA
entity Medico {
    * id
    --
    * matricula
    * nombre
    * apellido
}

entity Domicilio {
    * id
    --
    * calle
    * altura
}

entity Telefono {
    * id
    --
    * numero
}

entity Genero {
    * id
    --
    * descripcion
}

entity Paciente {
    * numero
    --
    * dni
    * nombre
    * apellido
    * id_sexo
    * id_domicilio
    * id_telefono
    * email
}

entity Estado {
    * id
    --
    * descripcion
}

entity Estudio {
    * id
    --
    * descripcion
    * rangos_de_referencias
    * id_metodo
    * id_unidad_de_medida
}

entity Solicitud {
    * id
    --
    * receta
    * id_paciente
    * id_extraccionista
    * id_estado
    * id_medico
    * fecha_inicio
    * fecha_finalizacion
    * CAP
}

entity Extraccionista {
    * id
    --
    * nombre
    * apellido
}

entity Muestra {
    * id
    --
    * descripcion
    * fecha
    * id_resultado
}

entity Metodo {
    * id
    --
    * descripcion
}

entity EstudioSolicitado {
    * id
    --
    * valor_hallado
    * fecha
    * id_estudio
    * observacion
}

entity UnidadDeMedida {
    * id
    --
    * unidad
}

Paciente ||..|| Domicilio
Paciente ||..|{ Telefono
Paciente }o..|| Genero
Paciente ||..|{ Solicitud
Solicitud }o..|| Medico
Solicitud }o..|| Estado
EstudioSolicitado ||..o| Muestra
Solicitud }o..|| Extraccionista
Estudio }o..|| Metodo
Solicitud }|..|{ EstudioSolicitado
Estudio }o..|| UnidadDeMedida
EstudioSolicitado }o..|| Estudio

@enduml